vars:
  namespace: orgs
  tenant: environment
  environment: development
  stage: eu-west-2

components:
  terraform:
    credit-risk-service:
      vars:
        cluster_name: credit-risk-dev-cluster
        task_family: credit-risk-api
        container_name: credit-risk-api
        container_image: credit-risk-api:latest
        container_port: 8000

        container_cpu: 256
        container_memory: 512

        environment: dev

        aws_region: eu-west-2
        aws_access_key: test
        aws_secret_key: test
        localstack_endpoint: http://localhost:4566