# Generated by Django 4.1.5 on 2026-01-27 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditLoans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loan_type",
                    models.CharField(
                        choices=[
                            ("poor", "Poor Credit"),
                            ("standard", "Standard Credit"),
                            ("good", "Good Credit"),
                        ],
                        default="non_specified_loan",
                        max_length=20,
                        verbose_name="loan type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CreditParameters",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("month", models.CharField(max_length=10)),
                ("occupation", models.CharField(max_length=100)),
                ("delay_from_due_date", models.CharField(max_length=10)),
                ("credit_mix", models.CharField(max_length=100)),
                ("payment_of_minimum_amount", models.CharField(max_length=10)),
                (
                    "payment_behaviour",
                    models.CharField(
                        choices=[
                            (
                                "low_spend_small_value_payments",
                                "Low Spend and small value payments",
                            ),
                            (
                                "low_spend_medium_value_payments",
                                "Low Spend and medium value payments",
                            ),
                            (
                                "low_spend_large_value_payments",
                                "Low Spend and large value payments",
                            ),
                            (
                                "high_spend_small_value_payments",
                                "High Spend and small value payments",
                            ),
                            (
                                "high_spend_medium_value_payments",
                                "High Spend and medium value payments",
                            ),
                            (
                                "high_spend_large_value_payments",
                                "High Spend and large value payments",
                            ),
                        ],
                        max_length=50,
                        verbose_name="payment behaviour",
                    ),
                ),
                ("changed_credit_limit", models.CharField(max_length=10)),
                ("credit_history_age", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("annual_income", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "monthly_in_hand_salary",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("number_of_bank_accounts", models.IntegerField()),
                ("number_of_credit_cards", models.IntegerField()),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("number_of_loans", models.IntegerField()),
                ("number_of_delayed_payment", models.IntegerField()),
                ("num_credit_inquiries", models.IntegerField()),
                (
                    "outstanding_debt",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credit_utilization_ratio",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "total_emi_per_month",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "amount_invested_monthly",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "monthly_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "credit_score",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("poor", "Poor Credit"),
                            ("standard", "Standard Credit"),
                            ("good", "Good Credit"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="qualification type",
                    ),
                ),
            ],
        ),
    ]
