# Generated by Django 4.1.5 on 2026-01-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="creditparameters", name="month",),
    ]
