# Generated by Django 4.1.5 on 2026-01-27 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculate", "0003_remove_creditparameters_month"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditparameters", name="credit_history_age",
        ),
    ]
